//! Crucible SSOT bindings for Rust
//!
//! This crate provides generated types and constants from the FulmenHQ Crucible
//! Single Source of Truth (SSOT) repository. These bindings are automatically
//! generated from YAML catalogs and JSON schemas.
//!
//! # Modules
//!
//! - [`foundry`] - Core constants and types (exit codes, etc.)
//!
//! # Usage
//!
//! ```rust
//! use crucible_codegen::foundry::ExitCode;
//!
//! fn main() {
//!     // Use standardized exit codes
//!     std::process::exit(ExitCode::Success.code());
//! }
//! ```
//!
//! # Generation
//!
//! This crate's contents are generated by the Crucible codegen pipeline.
//! Do not edit generated files directly - modify the source catalogs in
//! the Crucible repository root instead.
//!
//! See: <https://github.com/fulmenhq/crucible>

#![deny(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::all)]
#![warn(clippy::pedantic)]

pub mod foundry;
/// Fulencode encoding formats and types
pub mod fulencode;
/// Fulhash hashing algorithms and types
pub mod fulhash;
/// Fulpack archive formats and types
pub mod fulpack;

/// Crate version (matches Crucible release)
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
