//! Crucible SSOT bindings for Rust
//!
//! This crate provides generated types and constants from the FulmenHQ Crucible
//! Single Source of Truth (SSOT) repository. These bindings are automatically
//! generated from YAML catalogs and JSON schemas.
//!
//! # Modules
//!
//! - [`foundry`] - Core constants and types (exit codes, etc.)
//!
//! # Usage
//!
//! ```rust,no_run
//! use crucible_codegen::foundry::ExitCode;
//!
//! // Use standardized exit codes
//! let code = ExitCode::Success.code();
//! assert_eq!(code, 0);
//! ```
//!
//! # Generation
//!
//! This crate's contents are generated by the Crucible codegen pipeline.
//! Do not edit generated files directly - modify the source catalogs in
//! the Crucible repository root instead.
//!
//! See: <https://github.com/fulmenhq/crucible>

// =============================================================================
// Lint Configuration
// See: docs/standards/coding/rust.md and lang/rust/.clippy.toml
// =============================================================================

// Standard Safety & Quality
#![deny(unsafe_code)]
#![warn(missing_docs)]
#![warn(rust_2018_idioms)]
// Clippy Groups
#![warn(clippy::all)]
#![warn(clippy::pedantic)]
#![warn(clippy::cargo)]
// Allowances for generated code patterns
#![allow(clippy::module_name_repetitions)] // e.g., fulpack::types::ArchiveFormat
#![allow(clippy::multiple_crate_versions)] // Dependency tree may require this
#![allow(clippy::match_same_arms)] // category() method groups by category
#![allow(clippy::doc_markdown)] // FulmenHQ, ExitCode in docs (see .clippy.toml)

pub mod foundry;
/// Fulencode encoding formats and types
pub mod fulencode;
/// Fulhash hashing algorithms and types
pub mod fulhash;
/// Fulpack archive formats and types
pub mod fulpack;

/// Crate version (matches Crucible release)
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
