package fulhash

// Code generated by scripts/codegen/generate-fulhash-types.ts; DO NOT EDIT.

// Algorithm identifier
type Algorithm string

const (

	// XXH3 (128-bit)
	// Fast non-cryptographic hash (default). Excellent collision resistance, extremely high throughput (50GB/s+).
	XXH3_128 Algorithm = "xxh3-128"

	// SHA-256
	// Cryptographic security standard. Resistant to intentional collisions. Use for security verification.
	SHA256 Algorithm = "sha256"

	// CRC-32 (IEEE)
	// 32-bit Cyclic Redundancy Check. Standard for GZIP/ZIP/PNG legacy format interoperability.
	CRC32 Algorithm = "crc32"

	// CRC-32C (Castagnoli)
	// 32-bit CRC (Castagnoli). HW accelerated (SSE4.2/ARMv8). Use for cloud storage (GCS, AWS) and networking.
	CRC32C Algorithm = "crc32c"
)

// IsValid checks if the algorithm is supported
func (a Algorithm) IsValid() bool {
	switch a {
	case XXH3_128, SHA256, CRC32, CRC32C:
		return true
	}
	return false
}

// String returns the string representation
func (a Algorithm) String() string {
	return string(a)
}

// Standard digest payload returned by FulHash helpers
type Digest struct {
	// Hash algorithm identifier
	Algorithm string `json:"algorithm"`
	// Lowercase hexadecimal representation of the digest
	Hex string `json:"hex"`
	// Canonical string representation '<algorithm>:<hex>'
	Formatted string `json:"formatted"`
	// Raw digest bytes (optional)
	Bytes []byte `json:"bytes,omitempty"`
}
