/**
 * FulHash Types
 * Code generated by scripts/codegen/generate-fulhash-types.ts; DO NOT EDIT.
 */

/**
 * Supported hashing algorithms for FulHash
 */
export enum Algorithm {

  /**
   * XXH3 (128-bit)
   * Fast non-cryptographic hash (default). Excellent collision resistance, extremely high throughput (50GB/s+).
   */
  XXH3_128 = "xxh3-128",

  /**
   * SHA-256
   * Cryptographic security standard. Slower but resistant to intentional collisions. Use for security verification.
   */
  SHA256 = "sha256",

  /**
   * CRC-32 (IEEE)
   * 32-bit Cyclic Redundancy Check. Standard for GZIP, ZIP, PNG. Use for legacy format interoperability.
   */
  CRC32 = "crc32",

  /**
   * CRC-32C (Castagnoli)
   * 32-bit CRC with Castagnoli polynomial. Hardware accelerated on modern CPUs (SSE4.2/ARMv8). Use for cloud storage (GCS, AWS) and network protocols (SCTP, iSCSI).
   */
  CRC32C = "crc32c",

}


/**
 * Standard digest payload returned by FulHash helpers
 */
export interface Digest {

  /**
   * Hash algorithm identifier
   */
  algorithm: &#34;xxh3-128&#34; | &#34;crc32&#34; | &#34;crc32c&#34; | &#34;sha256&#34;;

  /**
   * Lowercase hexadecimal representation of the digest
   */
  hex: string;

  /**
   * Canonical string representation &#39;&lt;algorithm&gt;:&lt;hex&gt;&#39;
   */
  formatted: string;

  /**
   * Raw digest bytes (optional)
   */
  bytes?: number[];

}

